### ISSUE TITLE
Running on Unix: AttributeError: 'module' object has no attribute 'deque'

### ISSUE THREAD

**Issue by larsrinn** [pfalcon/notes-pico#3]
Following the instructions to run the app on Unix, I got this traceback. Probably this is not an issue on `notes_pico` but rather for `picoweb` or `uasyncio` ? Maybe there are some version incompatibilities involved?

```
Traceback (most recent call last):
  File "app/notes_pico/__main__.py", line 21, in <module>
  File "app/notes_pico/__main__.py", line 18, in main
  File "app/picoweb/__init__.py", line 283, in run
  File "app/uasyncio/core.py", line 224, in get_event_loop
  File "app/uasyncio/__init__.py", line 21, in __init__
  File "app/uasyncio/core.py", line 30, in __init__
AttributeError: 'module' object has no attribute 'deque'
```
I tried it on Ubuntu 16.04 running inside WSL and Ubuntu Mate on a Rasperry Pi...

**Comment by pfalcon** [comment]
Yes, please see https://forum.micropython.org/viewtopic.php?f=15&t=85&start=80#p25186

**Comment by larsrinn** [comment]
Great, works with your fork of Micropython...

**Comment by pfalcon** [comment]
I applied changes to the README: https://github.com/pfalcon/notes-pico/commit/910ef95c2b835b0d40f47056b84c24cb72c2e416 , and release new version on PyPI with it.

Let's keep this ticket open, as surely there will be more questions. (Forks are sad, sad thing...)
